### ISSUE TITLE
what is jlibrosa-1.0.4-SNAPSHOT-jar-with-dependencies.jar lib?

### ISSUE THREAD

**Issue by m1namuci** [VVasanth/Spleeter_Unofficial_TF20_MobileApp#2]
any source or reference, I'm looking for c++ or java implementation of librosa but found nothing

**Comment by VVasanth** [comment]
JLibrosa is a java equivalent of python's librosa...I am the author of it and I have written multiple blog post explaining how to use JLibrosa in Android app for processing audio files...refer them below...

1. https://github.com/Subtitle-Synchronizer/jlibrosa
2. https://heartbeat.fritz.ai/a-definitive-guide-for-audio-processing-in-android-with-tensorflow-lite-models-d90de896f0c4
3. https://heartbeat.fritz.ai/noise-classification-in-android-mobile-app-with-tensorflow-lite-13dede0f5d44

Pls let me know if you need any additional info...
